---
title: "Broker"
author: "Sebastian Castillo"
date: "17/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Fondos:
  20000 inmediatos para caución. 
    Fondo Comùn, Quinquela Ahorro, 55/60% anual, acreditación a las 24hs.
    Fonder: transferencia o deppòsito.
  11000 EU: qué opciones hay?
    Tener
  200000: Compra de acciones o títulos?
    REvisión

Objetivo:
  Trading para generar un ingreso mensual sostenido y en crecimiento.
  Primera Etapa (tres meses): familirización con plataforma y estudio de activos
  Segunda Etapa: posiciones más agresivas      

Asistencia
  Asesor? teléfono?
    Bruno Camisassa, 3434154720, contador, brunocamisassa@leivahnos.com.ar
    Ricardo Couchot, jefe de operaciones, por opcion!

Operatoria
  Ingreso-Egreso x Tercios

Comisiones:
  Cauciones: 6% anual? Ejemplo: 30000.
  Acciones: 0.7%
  Retiro de Dinero: llamar a Bruno o corro, costo transferenci $51. 

Plataforma:
  Habilitar Futuros y Opciones: SI
  Stopp Loss (actulización mensual? Cierra posición automáticamente?) - Take profit: Solicitar a Brunos
    
-Broker en el exterior TD Ameritrade
  Posibilidad de Habilitación: Septiembre.


_Inversion Dolares Letes, ON (ej. YPF).
_Dolar Bolsa: a partir de $20000.
_CobroyFondo: 10 dias. comisión 60%.


