---
title: "Analisis Entrada"
author: "Sebastian Castillo"
date: "13/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

#########################

Analisis Inicial

-SEMANA 1
día 1
1. Elegir accion (preferentemente lider del sector)
2. Estudiarla todo el día para aprehender su comportamiento (horarios, saltos, volúmenes, etc)
3. Detectar patrones
dia 2
4. Analizar correlación entre acción e indices disponibles. Ej. BYMA. ¿son armonicos? se adelanta uno a otro? 
5. Analizar otra acción del sector?
6. Comparar movimientos día2-dia1
6. Efectuar un informe AT (siguiendo las jerarquías). Explorar correlaciones, ver horas.
dia 3
7. Supervision de la acciones e índices.
dia 4
8. Analizar una nueva accion (3 en total).
9. Comparar las acciones y los índices.
dia 5
10. Supervisión de acciones e indices
11. Cierre de la Semana y Perspectivas próxima semana.

-SEMANA 2
1. Estudiar índice o indicadores anticipatorios. (ej. osciladores y divergencia)
2. Revisar MACD, RCI
3. Chequear ordenes de compra-venta y stop loss-take profit.

Estrategia Top-Down
Mercado, Indice del Sector, Acciones (en distintos marcos temporales, años, meses y días).

Establecer la relación riesgo-recompensa
precio de entrada: $20
stop loss: $19
precio objetivo: $23
riesgo-recompensa: 1:3

Momento de Compra: lista de chequeo
1. está en tendencia alcista?
2. la acción está sobre la MM50 y la MM200.
3. las MM están ordenadas: 20 encima 50 encima 200
4. hay volumen destacado?
5. MACD, Stocastico y CCI están hacia arriba, mostrando divergencia alcista?
- con todo confirmado-
6. Ingresar con 50 % de la posición ni bien se quiebre la resistencia. 
7. Terminar de tomar la posición con el 50 % restante luego de la recuperación del primer retroceso si hay confirmación de volumen.
8. Ajustar Stop loss
9. Fijar linea de tendencia alcista (ultimos puntos mínimos)

