---
title: "Sector Financiero - Ficha Técnica"
author: "Sebastian Castillo"
date: "12/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Resumen

El sector financiero es un sector importante dentro del BYMA.   

Los activos del sector mantiene una correlación positiva fuerte con el Índice S&P Merval y entre sí: GGAL, BMA, FRAN, SUPV, VALO y BYMA (PLideer); y Banco Hipotecario (BHIP), Banco Patagonia (BPAT), Banco Santander Rio (BRIO) y Banco Santander Hispano (PGeneral).

Todos estos activos tiene ADR, cotizan en NYE.

El desempeño del sector está estrechamente vinculado a la situación macroeconómica, situaciones de crisis financiera, inflación y cambios regulatorios afectan directamente su evolución. El sistema financiero argentino cuenta con una importante presencia de la banca pública nacional (i.e. Banco Nación).

Estudios empíricos señalan que los segmentos de población más rentables para el sector son los segmentos de altos ingresos, y en menor medida de ingresos medios. En estos segmentos los bancos con mayor participación 

# Fuentes
[BCRA: Informe sobre Bancos](http://www.bcra.gov.ar/PublicacionesEstadisticas/Informe_mensual_sobre_bancos.asp)     
[BCRA: Comparativo Bancos](http://www.bcra.gob.ar/PublicacionesEstadisticas/Entidades_financieras.asp?fecha=201904)

# Bibliografia
[-Competencia del sistema bancario argentino -modelo de Panzar-Rosse](http://www.bcra.gov.ar/institucional/DescargaPDF/DownloadPDF.aspx?Id=605)
