---
title: "Sector Gasífero - Ficha Técnica"
author: "Sebastian Castillo"
date: "12/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Resumen

Los activos del sector mantiene una correlación débil con el Índice S&P Merval:    
Industrias Gasíferas: TGSU2, TGNO4, DGCU2

Los drivers del sector mas importante son:
-Política de Tarifas: la política tarifaria es un determinante fundamental en las cotizaciones de estos activos. Las empresas de servicios públicos son las primeras afectadas por esta política: al tener precios regulados, su situación depende en gran medida de las decisiones del gobierno. Por períodos prolongados el congelamiento de tarifas determinó una subvaloración de las acciones del sector. En este caso la mira está puesta en el Congreso. 
-Decisiones Judiciales: los fallos sobre tarifas, (im)posibilidad de suspensión de suministro por cuestiones de pago, etc, repercuten sobre la cotización.
-Ínterés y Tipo de cambio: muchas de estas empresas financian sus proyectos tomando deuda así que las subas de interés (y el crecimiento de los pasivos) pueden afectar a la baja las cotizaciones. Las firmas más comprometidas ante un eventual cambio de escenario son las distribuidoras gasíferas: Gas Ban, Distribuidora de Gas Cuyana, Metrogas y Camuzzi.

Muchos de estos activos tiene ADR, cotizan en NYE: YPF, CEPU, otros.

Algunos Activos;:


# Fuentes
[]()     

# Bibliografia
[]()     
